### ISSUE TITLE
Rename PubMedId nodes to PaperID

### ISSUE THREAD

**Issue by motey** [covidgraph/data_clinical-trials-gov#2]
From the CORD19 dataloader we allready have nodes with different external IDs for papers/articles names "PaperID" 
`MATCH (n:PaperID) RETURN n LIMIT 25`. Some of these are Pubmed ids.
On the other hand we have `PubMedId`nodes in the clinicals trial loder. 
`MATCH (n:PubMedId) RETURN n LIMIT 25`

 It would make sense to adapt the clinical trials id to the cord19 scheme. This would connect the clinical trials and the cord19 datasets nicely. 

The PaperID nodes have 2 properties. the `id`property is the id itself. in the PubMedId nodes this is the property `name`. 
The second property is `type` which contains the string `pubmed_id`for pubmed ids.

**Comment by yGuy** [comment]
@motey - do you think you could do this (I am positive you will be able to do this in a few minutes) - this is a low-hanging fruit that would really help the explorer to become even more useful, I guess.

**Comment by KirstenLangendorf** [comment]
I already fixed it. Informed Tim back on Aug-10. Let me know if it is not as you wanted it.

**Comment by yGuy** [comment]
Awesome, thanks @KirstenLangendorf  - is this on dev or prod, already @motey ? Then we should close the issue. I was waiting for the issue notification to continue work on this!

**Comment by motey** [comment]
still not on both. i was busy rewriting the pipeline and setting the new infrastructure. 
this is next on my todo list :)

**Comment by motey** [comment]
manually fixed it for existing data on PROD and DEV
```cypher
MATCH (n:PubMedId) 
SET n.id=n.name
SET n.type='pubmed_id'
REMOVE n.name
return true;
```
```cypher
MATCH (n)
where n:PubMedId OR n:PaperID
WITH n.id as id, COLLECT(n) AS ns
WHERE size(ns) > 1
CALL apoc.refactor.mergeNodes(ns) YIELD node
RETURN true;
```

```cypher
MATCH (n:PubMedId)
REMOVE n:PubMedId
return true;
``` 

Next pipeline run will create the new model from the beginning.
